openapi: 3.0.2
info:
  version: 1.0.0
  contact:
    email: jardelgoncalves1996@gmail.com
    url: 'https://jardelgoncalves.dev'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: '/favicon.png'
  description: >
    An sample
tags:
  - name: Deals
    description: Deals need to have won status to generate bling orders
  - name: Log
    description: Logs of application
servers:
  - url: 'http://localhot:3333'
paths:
  /deals:
    $ref: paths/deals.yaml
  /logs:
    $ref: paths/log.yaml
